#!/usr/bin/env bash

#
# prep-airdrop.sh - Mac Mini Dev Server Deployment Package Preparation
#
# This script creates a comprehensive deployment package for Mac Mini dev server setup by:
# - Managing 1Password credential retrieval and secure transfer via external keychain
# - Creating hardware fingerprint validation to prevent accidental execution
# - Configuring WiFi credentials (manual or Migration Assistant strategies)
# - Generating deployment manifest for package validation
# - Copying all setup scripts and configurations
# - Processing environment-specific configurations
#
# REQUIREMENTS:
# - 1Password CLI (op) installed and authenticated: `op signin`
# - Required 1Password vault items: TimeMachine, Apple ID
# - SSH keys present at ~/.ssh/id_ed25519 and ~/.ssh/id_ed25519.pub
# - jq, openssl, system_profiler, security commands available
# - Administrator privileges for WiFi keychain access
# - Valid config/config.conf file (copy from config.conf.template)
#
# Usage: ./prep-airdrop.sh [output_path] [script_path]
#   output_path    Directory where deployment package will be created
#                  (default: ~/${SERVER_NAME_LOWER}-setup)
#   script_path    Source directory containing scripts (default: current directory)
#   --help, -h     Show detailed usage information
#
# INTERACTIVE PROMPTS:
# - WiFi setup strategy selection (Migration Assistant vs script-based)
# - Existing directory overwrite confirmation
# - 1Password credential retrieval (if missing)
#
# ENVIRONMENT VARIABLES (Optional):
# - USE_ITERM2: Set to "true" to export iTerm2 preferences
# - TERMINAL_PROFILE_FILE: Terminal profile filename to include
#
# SECURITY FEATURES:
# - Hardware UUID fingerprint prevents wrong-machine execution
# - One-time Apple ID password links with expiration
# - Secure memory clearing for sensitive variables
# - External keychain with hardware-based password protection
# - Proper file permissions (600) for sensitive configuration files
#
# OUTPUT:
# - Complete deployment package ready for AirDrop transfer
# - Deploy manifest for target server validation
# - Encrypted credential keychain for secure transfer
# - Configuration files with environment-specific substitutions
#
# Author: Andrew Rich <andrew.rich@gmail.com>
# Created: 2025-05-13

# Exit on error
set -euo pipefail

# Configuration
SCRIPT_SOURCE_DIR="${2:-.}" # Directory containing source scripts (default is current dir)

# Load configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${SCRIPT_DIR}" # Script is now at repo root
CONFIG_DIR="${PROJECT_ROOT}/config"
CONFIG_FILE="${CONFIG_DIR}/config.conf"

CONFIG_TEMPLATE="${CONFIG_DIR}/config.conf.template"

if [[ ! -f "${CONFIG_FILE}" ]]; then
  if [[ ! -f "${CONFIG_TEMPLATE}" ]]; then
    echo "Error: No config.conf or config.conf.template found in ${CONFIG_DIR}"
    exit 1
  fi

  echo "No config.conf found — let's create one."
  echo ""

  # Source template for defaults
  # shellcheck source=/dev/null
  source "${CONFIG_TEMPLATE}"

  # Prompt for essential values (Enter accepts the default shown in brackets)
  read -r -p "Server name [${SERVER_NAME}]: " input
  SERVER_NAME="${input:-${SERVER_NAME}}"

  read -r -p "1Password vault [${ONEPASSWORD_VAULT}]: " input
  ONEPASSWORD_VAULT="${input:-${ONEPASSWORD_VAULT}}"

  read -r -p "1Password Apple ID item name [${ONEPASSWORD_APPLEID_ITEM}]: " input
  ONEPASSWORD_APPLEID_ITEM="${input:-${ONEPASSWORD_APPLEID_ITEM}}"

  read -r -p "1Password Time Machine item name [${ONEPASSWORD_TIMEMACHINE_ITEM}]: " input
  ONEPASSWORD_TIMEMACHINE_ITEM="${input:-${ONEPASSWORD_TIMEMACHINE_ITEM}}"

  read -r -p "Dotfiles repo (SSH URL, or empty to skip) [${DOTFILES_REPO}]: " input
  DOTFILES_REPO="${input:-${DOTFILES_REPO}}"

  read -r -p "Monitoring email [${MONITORING_EMAIL}]: " input
  MONITORING_EMAIL="${input:-${MONITORING_EMAIL}}"

  # Write config.conf from collected values
  generated_date="$(date '+%Y-%m-%d')"

  cat >"${CONFIG_FILE}" <<CONF
# config.conf - Generated by prep-airdrop.sh on ${generated_date}

# Server identity
SERVER_NAME="${SERVER_NAME}"

# 1Password configuration
ONEPASSWORD_VAULT="${ONEPASSWORD_VAULT}"
ONEPASSWORD_APPLEID_ITEM="${ONEPASSWORD_APPLEID_ITEM}"
ONEPASSWORD_TIMEMACHINE_ITEM="${ONEPASSWORD_TIMEMACHINE_ITEM}"
SSH_KEY_ITEM="${SSH_KEY_ITEM:-SSH Keys}"

# Monitoring
MONITORING_EMAIL="${MONITORING_EMAIL}"

# Development configuration
DOTFILES_REPO="${DOTFILES_REPO}"
ANDROID_SDK_VERSION="${ANDROID_SDK_VERSION:-34}"
NODE_VERSION="${NODE_VERSION:-lts}"
XCODE_VERSION="${XCODE_VERSION:-}"

# Terminal configuration (optional)
TERMINAL_PROFILE_FILE="${TERMINAL_PROFILE_FILE:-}"
USE_ITERM2="${USE_ITERM2:-false}"

# Optional overrides
HOSTNAME_OVERRIDE="${HOSTNAME_OVERRIDE:-}"
CONF

  echo ""
  echo "Created ${CONFIG_FILE}"
fi

# shellcheck source=/dev/null
source "${CONFIG_FILE}"
echo "Loaded configuration from ${CONFIG_FILE}"
echo "Validating configuration..."

# Validate required config variables
: "${SERVER_NAME:?SERVER_NAME must be set in config.conf}"
: "${ONEPASSWORD_VAULT:?ONEPASSWORD_VAULT must be set in config.conf}"
: "${ONEPASSWORD_TIMEMACHINE_ITEM:?ONEPASSWORD_TIMEMACHINE_ITEM must be set in config.conf}"
: "${ONEPASSWORD_APPLEID_ITEM:?ONEPASSWORD_APPLEID_ITEM must be set in config.conf}"

# Handle command line arguments
if [[ "${1:-}" == "--help" ]] || [[ "${1:-}" == "-h" ]]; then
  echo "Usage: $(basename "$0") [output_path] [script_path]"
  echo ""
  echo "Prepares setup files for Mac Mini server deployment."
  echo ""
  echo "Arguments:"
  echo "  output_path    Directory where setup files will be created (default: ~/${SERVER_NAME_LOWER:-server}-setup)"
  echo "  script_path    Source directory containing scripts (default: current directory)"
  echo ""
  echo "The prepared directory can be AirDropped to your Mac Mini for setup."
  exit 0
fi

# Error and warning collection system
COLLECTED_ERRORS=()
COLLECTED_WARNINGS=()
CURRENT_SCRIPT_SECTION=""

# Function to set current script section for context
set_section() {
  CURRENT_SCRIPT_SECTION="$1"
  echo "====== $1 ======"
}

# Function to collect an error (with immediate display)
collect_error() {
  local message="$1"
  local line_number="${2:-${LINENO}}"
  local context="${CURRENT_SCRIPT_SECTION:-Unknown section}"
  local script_name
  script_name="$(basename "${BASH_SOURCE[1]:-${0}}")"

  # Normalize message to single line (replace newlines with spaces)
  local clean_message
  clean_message="$(echo "${message}" | tr '\n' ' ' | sed 's/[[:space:]]\+/ /g' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')"

  echo "❌ ${clean_message}"
  COLLECTED_ERRORS+=("[${script_name}:${line_number}] ${context}: ${clean_message}")
}

# Function to collect a warning (with immediate display)
collect_warning() {
  local message="$1"
  local line_number="${2:-${LINENO}}"
  local context="${CURRENT_SCRIPT_SECTION:-Unknown section}"
  local script_name
  script_name="$(basename "${BASH_SOURCE[1]:-${0}}")"

  # Normalize message to single line (replace newlines with spaces)
  local clean_message
  clean_message="$(echo "${message}" | tr '\n' ' ' | sed 's/[[:space:]]\+/ /g' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')"

  echo "⚠️ ${clean_message}"
  COLLECTED_WARNINGS+=("[${script_name}:${line_number}] ${context}: ${clean_message}")
}

# Function to show collected errors and warnings at end
show_collected_issues() {
  local error_count=${#COLLECTED_ERRORS[@]}
  local warning_count=${#COLLECTED_WARNINGS[@]}

  if [[ ${error_count} -eq 0 && ${warning_count} -eq 0 ]]; then
    echo "✅ AirDrop preparation completed successfully with no errors or warnings!"
    return
  fi

  echo ""
  echo "====== AIRDROP PREPARATION SUMMARY ======"
  echo "Preparation completed, but ${error_count} errors and ${warning_count} warnings occurred:"
  echo ""

  if [[ ${error_count} -gt 0 ]]; then
    echo "ERRORS:"
    for error in "${COLLECTED_ERRORS[@]}"; do
      echo "  ${error}"
    done
    echo ""
  fi

  if [[ ${warning_count} -gt 0 ]]; then
    echo "WARNINGS:"
    for warning in "${COLLECTED_WARNINGS[@]}"; do
      echo "  ${warning}"
    done
    echo ""
  fi

  echo "Review issues above - some warnings may be expected if optional components are missing."
}

# Deploy Package Manifest Functions
# These functions create and maintain a manifest of all files in the deploy package
# to enable validation on the target server before deployment begins
# Note: copy_with_manifest and copy_dir_with_manifest will be used in subsequent integration

# Initialize deployment package manifest
init_manifest() {
  local manifest_file="${OUTPUT_PATH}/DEPLOY_MANIFEST.txt"
  local timestamp
  timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  cat >"${manifest_file}" <<EOF
# DEPLOY_MANIFEST.txt - Generated by prep-airdrop.sh
# This file lists all files that should be present in the deployment package
# Format: relative_path=REQUIRED|OPTIONAL|MISSING
MANIFEST_VERSION=1.0
CREATED_BY=prep-airdrop.sh
CREATED_AT=${timestamp}
PACKAGE_ROOT=${OUTPUT_PATH}

EOF
  echo "📋 Initialized deploy manifest: ${manifest_file}"
}

# Add file entry to manifest
add_to_manifest() {
  local file_path="$1"   # Relative path from OUTPUT_PATH
  local requirement="$2" # REQUIRED, OPTIONAL, or MISSING
  local manifest_file="${OUTPUT_PATH}/DEPLOY_MANIFEST.txt"

  echo "${file_path}=${requirement}" >>"${manifest_file}"
}

# Remove file entry from manifest
remove_from_manifest() {
  local file_path="$1"   # Relative path from OUTPUT_PATH
  local requirement="$2" # REQUIRED, OPTIONAL, or MISSING
  local manifest_file="${OUTPUT_PATH}/DEPLOY_MANIFEST.txt"

  if [[ ! -f "${manifest_file}" ]]; then
    echo "Manifest file does not exist: ${manifest_file}"
    return 1
  fi

  # Form the line to remove
  local entry="${file_path}=${requirement}"

  # Safely remove the exact matching line
  # (using a temp file to ensure atomic operation)
  local tmpfile
  tmpfile="$(mktemp "${manifest_file}.XXXXXX")"

  grep -vxF -- "${entry}" "${manifest_file}" >"${tmpfile}" && mv "${tmpfile}" "${manifest_file}"
}

# Copy file with manifest tracking
copy_with_manifest() {
  local source="$1"
  local dest_relative="$2" # Relative to OUTPUT_PATH
  local requirement="$3"   # REQUIRED or OPTIONAL

  local dest_full="${OUTPUT_PATH}/${dest_relative}"

  if [[ -f "${source}" ]]; then
    mkdir -p "$(dirname "${dest_full}")"
    cp "${source}" "${dest_full}"
    add_to_manifest "${dest_relative}" "${requirement}"
    echo "✅ Copied to manifest: ${dest_relative}"
  else
    if [[ "${requirement}" == "REQUIRED" ]]; then
      collect_error "Required file not found for deployment: ${source}"
      add_to_manifest "${dest_relative}" "MISSING"
    else
      collect_warning "Optional file not found: ${source}"
      add_to_manifest "${dest_relative}" "MISSING"
    fi
  fi
}

copy_dir_with_manifest() {
  local source_dir="$1"
  local dest_dir_relative="$2"      # Relative to OUTPUT_PATH
  local requirement="$3"            # REQUIRED or OPTIONAL
  local except_dirs_string="${4:-}" # e.g. ".git|.claude|tmp" or ""

  local dest_dir_full="${OUTPUT_PATH}/${dest_dir_relative}"

  # Prepare array of exception dirs if except_dirs_string is non-empty
  local IFS='|'
  read -r -a except_dirs <<<"${except_dirs_string}"

  if [[ -d "${source_dir}" ]]; then
    mkdir -p "${dest_dir_full}"

    # Copy directory contents and track individual files
    if find "${source_dir}" -type f -print0 | while IFS= read -r -d '' file; do
      local relative_to_source="${file#"${source_dir}/"}"
      local skip_file=0

      # For each file, check if it matches any exclude directory
      for exclude in "${except_dirs[@]}"; do
        # Only skip if file is inside an excluded dir (prefix match)
        if [[ "${relative_to_source}" == "${exclude}/"* ]] || [[ "${relative_to_source}" == "${exclude}" ]]; then
          skip_file=1
          break
        fi
      done

      if [[ ${skip_file} -eq 1 ]]; then
        continue
      fi

      local dest_file="${dest_dir_full}/${relative_to_source}"

      mkdir -p "$(dirname "${dest_file}")"
      cp "${file}" "${dest_file}"
      add_to_manifest "${dest_dir_relative}/${relative_to_source}" "${requirement}"
    done; then
      echo "✅ Copied directory to manifest: ${dest_dir_relative}/"
    else
      if [[ "${requirement}" == "REQUIRED" ]]; then
        collect_error "Failed to copy required directory: ${source_dir}"
      else
        collect_warning "Failed to copy optional directory: ${source_dir}"
      fi
    fi
  else
    if [[ "${requirement}" == "REQUIRED" ]]; then
      collect_error "Required directory not found for deployment: ${source_dir}"
    else
      collect_warning "Optional directory not found: ${source_dir}"
    fi
  fi
}

# Set derived variables
SERVER_NAME_LOWER="$(tr '[:upper:]' '[:lower:]' <<<"${SERVER_NAME}")"
OUTPUT_PATH="${1:-${HOME}/${SERVER_NAME_LOWER}-setup}"
OP_TIMEMACHINE_ENTRY="${ONEPASSWORD_TIMEMACHINE_ITEM}"

# Check if output directory exists
if [[ -d "${OUTPUT_PATH}" ]]; then
  echo "Output directory already exists: ${OUTPUT_PATH}"
  echo "This directory contains files from a previous preparation run."
  read -p "Remove existing directory and recreate? (y/N) " -n 1 -r
  echo
  if [[ ${REPLY} =~ ^[Yy]$ ]]; then
    echo "Removing existing directory..."
    rm -rf "${OUTPUT_PATH}"
    echo "Creating fresh output directory: ${OUTPUT_PATH}"
    mkdir -p "${OUTPUT_PATH}"
  else
    echo "Keeping existing directory. Files may be overwritten during preparation."
  fi
else
  echo "Creating output directory: ${OUTPUT_PATH}"
  mkdir -p "${OUTPUT_PATH}"
fi

set_section "Preparing ${SERVER_NAME} Server Setup Files for AirDrop"
echo "Output path: ${OUTPUT_PATH}"
echo -n "Date: "
date

# Create directory structure
set_section "Creating Directory Structure"
mkdir -p "${OUTPUT_PATH}/ssh_keys"
mkdir -p "${OUTPUT_PATH}/scripts"
mkdir -p "${OUTPUT_PATH}/app-setup/config"
mkdir -p "${OUTPUT_PATH}/config"
mkdir -p "${OUTPUT_PATH}/bash"

# Initialize deployment package manifest
init_manifest

# Generate development machine fingerprint to prevent accidental execution
DEV_FINGERPRINT=$(system_profiler SPHardwareDataType | grep "Hardware UUID" | awk '{print $3}')
if [[ -n "${DEV_FINGERPRINT}" ]]; then
  echo "Development machine fingerprint: ${DEV_FINGERPRINT}"
  echo "DEV_MACHINE_FINGERPRINT=\"${DEV_FINGERPRINT}\"" >"${OUTPUT_PATH}/config/dev_fingerprint.conf"
  chmod 600 "${OUTPUT_PATH}/config/dev_fingerprint.conf"
  add_to_manifest "config/dev_fingerprint.conf" "REQUIRED"
  echo "Development fingerprint saved to prevent accidental execution on this machine"
else
  collect_error "Could not generate development machine fingerprint"
  exit 1
fi

# Remove existing server host key if any
ssh-keygen -R "${SERVER_NAME_LOWER}".local

# Copy SSH keys
set_section "Copying SSH Keys"
SSH_PUBLIC_KEY_PATH="${HOME}/.ssh/id_ed25519.pub"
SSH_PRIVATE_KEY_PATH="${HOME}/.ssh/id_ed25519"

echo "Copying SSH keys..."
copy_with_manifest "${SSH_PUBLIC_KEY_PATH}" "ssh_keys/authorized_keys" "REQUIRED"
copy_with_manifest "${SSH_PUBLIC_KEY_PATH}" "ssh_keys/id_ed25519.pub" "REQUIRED"
copy_with_manifest "${SSH_PRIVATE_KEY_PATH}" "ssh_keys/id_ed25519" "REQUIRED"

# Set correct permissions on private key if it was copied
if [[ -f "${OUTPUT_PATH}/ssh_keys/id_ed25519" ]]; then
  chmod 600 "${OUTPUT_PATH}/ssh_keys/id_ed25519"
fi

# WiFi Configuration Strategy Selection
set_section "WiFi Network Configuration Strategy"
echo "Choose your WiFi setup method:"
echo "1. Migration Assistant iPhone/iPad option (recommended - handles WiFi automatically)"
echo "2. Script-based WiFi configuration (retrieves current network credentials)"
echo ""
read -p "Will you use Migration Assistant's iPhone/iPad option for WiFi? (Y/n) " -n 1 -r WIFI_STRATEGY
echo ""

if [[ ${WIFI_STRATEGY} =~ ^[Nn]$ ]]; then
  echo "Selected: Script-based WiFi configuration"
  echo "Getting current WiFi network information..."
  CURRENT_SSID=$(system_profiler SPAirPortDataType | awk '/Current Network/ {getline;$1=$1;print $0 | "tr -d \":\"";exit}' 2>/dev/null || echo "")

  if [[ -n "${CURRENT_SSID}" ]]; then
    echo "Current WiFi network SSID: ${CURRENT_SSID}"

    echo "Retrieving WiFi password..."
    echo "You'll be prompted for your administrator password to access the keychain."
    WIFI_PASSWORD=$(security find-generic-password -a "${CURRENT_SSID}" -w "/Library/Keychains/System.keychain")

    if [[ -n "${WIFI_PASSWORD}" ]]; then
      echo "WiFi password retrieved successfully."

      # Store WiFi credentials in external keychain
      store_external_keychain_credential \
        "wifi-${SERVER_NAME_LOWER}" \
        "${SERVER_NAME_LOWER}" \
        "${CURRENT_SSID}:${WIFI_PASSWORD}" \
        "Mac Server Setup - WiFi Credentials"

      # Create basic SSID config file (non-sensitive)
      cat >"${OUTPUT_PATH}/config/wifi_network.conf" <<EOF
WIFI_SSID="${CURRENT_SSID}"
EOF
      chmod 644 "${OUTPUT_PATH}/config/wifi_network.conf"

      # Clear password from memory
      unset WIFI_PASSWORD
      echo "WiFi credentials stored in Keychain and SSID saved to config"
    else
      collect_error "Could not retrieve WiFi password"
      echo "WiFi network configuration will not be automated."
    fi
  else
    collect_warning "Could not detect current WiFi network"
    echo "WiFi network configuration will not be automated."
  fi
else
  echo "Selected: Migration Assistant WiFi configuration"
  echo "✅ Migration Assistant will handle WiFi network setup automatically"
  echo "No WiFi credentials will be transferred to the setup package"
fi

# External keychain credential management functions
# Create and manage external keychain for credential transfer

# Initialize external keychain for credential storage
init_external_keychain() {
  # Use existing dev machine fingerprint as keychain password (dynamically generated, not hardcoded)
  KEYCHAIN_PASSWORD="${DEV_FINGERPRINT}"
  EXTERNAL_KEYCHAIN="mac-server-setup"

  echo "Initializing external keychain for credential transfer..."

  # Delete existing keychain if present
  security delete-keychain "${EXTERNAL_KEYCHAIN}" 2>/dev/null || true

  # Create new external keychain
  if security create-keychain -p "${KEYCHAIN_PASSWORD}" "${EXTERNAL_KEYCHAIN}"; then
    echo "✅ External keychain created"
  else
    collect_error "Failed to create external keychain"
    return 1
  fi

  # Unlock the keychain for credential storage
  if security unlock-keychain -p "${KEYCHAIN_PASSWORD}" "${EXTERNAL_KEYCHAIN}"; then
    echo "✅ External keychain unlocked for credential storage"
  else
    collect_error "Failed to unlock external keychain"
    return 1
  fi

  return 0
}

# Store credential in external keychain with immediate verification
store_external_keychain_credential() {
  local service="$1"
  local account="$2"
  local password="$3"
  local description="$4"

  # Delete existing credential if present (for updates)
  security delete-generic-password -s "${service}" -a "${account}" "${EXTERNAL_KEYCHAIN}" 2>/dev/null || true

  # Store in external keychain
  # Note: -A flag allows any application access without prompting, required for transfer
  if security add-generic-password \
    -s "${service}" \
    -a "${account}" \
    -w "${password}" \
    -D "${description}" \
    -A \
    -U \
    "${EXTERNAL_KEYCHAIN}"; then

    # Immediately verify by reading back from external keychain
    local retrieved_password
    if retrieved_password=$(security find-generic-password \
      -s "${service}" \
      -a "${account}" \
      -w \
      "${EXTERNAL_KEYCHAIN}" 2>/dev/null); then

      if [[ "${password}" == "${retrieved_password}" ]]; then
        echo "✅ Credential stored and verified in external keychain: ${service}"
        return 0
      else
        collect_error "External keychain credential verification failed for ${service}"
        return 1
      fi
    else
      collect_error "External keychain credential verification failed for ${service}: could not retrieve"
      return 1
    fi
  else
    collect_error "Failed to store credential in external keychain: ${service}"
    return 1
  fi
}

# Finalize external keychain and add to airdrop package
finalize_external_keychain() {
  echo "Finalizing external keychain for transfer..."

  # Lock the external keychain
  security lock-keychain "${EXTERNAL_KEYCHAIN}"

  # Get the keychain file path (macOS creates keychains with -db suffix)
  local keychain_file="${HOME}/Library/Keychains/${EXTERNAL_KEYCHAIN}-db"

  if [[ -f "${keychain_file}" ]]; then
    # Copy keychain file to airdrop package
    copy_with_manifest "${keychain_file}" "config/${EXTERNAL_KEYCHAIN}-db" "REQUIRED"
    chmod 600 "${OUTPUT_PATH}/config/${EXTERNAL_KEYCHAIN}-db"

    echo "✅ External keychain added to airdrop package"
    echo "   Keychain file: ${EXTERNAL_KEYCHAIN}-db"
    echo "   Password: Hardware UUID fingerprint"

    # Store keychain password in manifest for server use
    echo "KEYCHAIN_PASSWORD=\"${KEYCHAIN_PASSWORD}\"" >>"${OUTPUT_PATH}/config/keychain_manifest.conf"
    echo "EXTERNAL_KEYCHAIN=\"${EXTERNAL_KEYCHAIN}\"" >>"${OUTPUT_PATH}/config/keychain_manifest.conf"

    return 0
  else
    collect_error "External keychain file not found: ${keychain_file}"
    return 1
  fi
}

# Create Keychain manifest for server
create_keychain_manifest() {
  cat >"${OUTPUT_PATH}/config/keychain_manifest.conf" <<EOF
# External keychain service identifiers for credential retrieval
KEYCHAIN_TIMEMACHINE_SERVICE="timemachine-${SERVER_NAME_LOWER}"
KEYCHAIN_WIFI_SERVICE="wifi-${SERVER_NAME_LOWER}"
KEYCHAIN_ACCOUNT="${SERVER_NAME_LOWER}"
EOF
  chmod 600 "${OUTPUT_PATH}/config/keychain_manifest.conf"
  add_to_manifest "config/keychain_manifest.conf" "REQUIRED"
  echo "✅ Keychain manifest created"
}

# Initialize external keychain for credential storage
set_section "Setting up credentials"
init_external_keychain

# Set up Time Machine credentials using 1Password
echo "Setting up Time Machine credentials..."

# Check if Time Machine credentials exist in 1Password
if ! op item get "${OP_TIMEMACHINE_ENTRY}" --vault "${ONEPASSWORD_VAULT}" >/dev/null 2>&1; then
  echo "⚠️ Time Machine credentials not found in 1Password"
  echo "Please create '${OP_TIMEMACHINE_ENTRY}' entry manually"
  echo "Skipping Time Machine credential setup"
else
  echo "✅ Found Time Machine credentials in 1Password"

  # Retrieve Time Machine details from 1Password
  echo "Retrieving Time Machine details from 1Password..."
  TM_USERNAME=$(op item get "${OP_TIMEMACHINE_ENTRY}" --vault "${ONEPASSWORD_VAULT}" --fields username)
  TM_PASSWORD=$(op read "op://${ONEPASSWORD_VAULT}/${OP_TIMEMACHINE_ENTRY}/password")
  TM_JSON=$(op item get "${OP_TIMEMACHINE_ENTRY}" --vault "${ONEPASSWORD_VAULT}" --format json)
  TM_URL=$(echo "${TM_JSON}" | jq -r '.urls[0].href')

  # Store TimeMachine credentials in external keychain (username:password format)
  store_external_keychain_credential \
    "timemachine-${SERVER_NAME_LOWER}" \
    "${SERVER_NAME_LOWER}" \
    "${TM_USERNAME}:${TM_PASSWORD}" \
    "Mac Server Setup - TimeMachine Credentials"

  # Create basic URL config file (non-sensitive)
  cat >"${OUTPUT_PATH}/config/timemachine.conf" <<EOF
TM_URL="${TM_URL}"
EOF
  chmod 644 "${OUTPUT_PATH}/config/timemachine.conf"
  add_to_manifest "config/timemachine.conf" "REQUIRED"

  # Clear credentials from memory
  unset TM_USERNAME TM_PASSWORD
  echo "✅ Time Machine credentials stored in Keychain"
fi

# Create and save one-time link for Apple ID password
APPLE_ID_ITEM="$(op item list --categories Login --vault "${ONEPASSWORD_VAULT}" --favorite --format=json 2>/dev/null | jq -r '.[] | select(.title == "'"${ONEPASSWORD_APPLEID_ITEM}"'") | .id' 2>/dev/null || echo "")"
ONE_TIME_URL="$(op item share "${APPLE_ID_ITEM}" --view-once)"
if [[ -n "${ONE_TIME_URL}" ]]; then
  # Create the .url file with the correct format
  cat >"${OUTPUT_PATH}/config/apple_id_password.url" <<EOF
[InternetShortcut]
URL=${ONE_TIME_URL}
EOF
  chmod 600 "${OUTPUT_PATH}/config/apple_id_password.url"
  add_to_manifest "config/apple_id_password.url" "OPTIONAL"
  echo "✅ Apple ID one-time password link saved to config/apple_id_password.url"
else
  echo "⚠️ No URL provided, skipping Apple ID password link creation"
fi

# Copy from local script source directory
if [[ -d "${SCRIPT_SOURCE_DIR}" ]]; then
  set_section "Copying scripts from local source directory"

  # Copy main entry point script to root
  copy_with_manifest "${SCRIPT_SOURCE_DIR}/scripts/server/first-boot.sh" "first-boot.sh" "REQUIRED" || collect_warning "first-boot.sh not found in server directory"
  chmod +x "${OUTPUT_PATH}/first-boot.sh" 2>/dev/null

  # Copy all server scripts to scripts directory (excluding first-boot.sh which goes to root)
  echo "Copying all server scripts to deployment package..."
  for script in "${SCRIPT_SOURCE_DIR}/scripts/server/"*.sh; do
    script_name="$(basename "${script}")"
    # Skip first-boot.sh as it's handled separately
    if [[ "${script_name}" != "first-boot.sh" ]]; then
      if copy_with_manifest "${script}" "scripts/${script_name}" "REQUIRED"; then
        chmod +x "${OUTPUT_PATH}/scripts/${script_name}"
        echo "  ✅ ${script_name}"
      else
        echo "  ❌ Failed to copy ${script_name}"
      fi
    fi
  done

  # Copy app setup scripts to app-setup directory
  echo "Copying app setup scripts..."
  for app_script in "${SCRIPT_SOURCE_DIR}/app-setup/"*.sh; do
    if [[ -f "${app_script}" ]]; then
      script_name="$(basename "${app_script}")"
      copy_with_manifest "${app_script}" "app-setup/${script_name}" "REQUIRED"
      chmod +x "${OUTPUT_PATH}/app-setup/${script_name}"
      echo "  ✅ ${script_name}"
    fi
  done

  # Copy system configuration files
  copy_with_manifest "${SCRIPT_SOURCE_DIR}/config/formulae.txt" "config/formulae.txt" "REQUIRED" || echo "Warning: formulae.txt not found in source directory"
  copy_with_manifest "${SCRIPT_SOURCE_DIR}/config/casks.txt" "config/casks.txt" "REQUIRED" || echo "Warning: casks.txt not found in source directory"
  copy_with_manifest "${SCRIPT_SOURCE_DIR}/config/logrotate.conf" "config/logrotate.conf" "OPTIONAL" || echo "Warning: logrotate.conf not found in source directory"

  # Copy configuration file (validated at startup)
  copy_with_manifest "${CONFIG_FILE}" "config/config.conf" "REQUIRED"
  echo "Configuration file copied to setup package"

  # Copy terminal profile files if specified in configuration
  if [[ -n "${TERMINAL_PROFILE_FILE:-}" ]]; then
    terminal_src="${CONFIG_DIR}/${TERMINAL_PROFILE_FILE}"
    if [[ -f "${terminal_src}" ]]; then
      copy_with_manifest "${terminal_src}" "config/${TERMINAL_PROFILE_FILE}" "OPTIONAL"
      echo "Terminal profile copied to deployment package: ${TERMINAL_PROFILE_FILE}"
    else
      echo "Warning: Terminal profile file not found: ${terminal_src}"
    fi
  fi

  # Export iTerm2 preferences if requested
  if [[ "${USE_ITERM2:-false}" == "true" ]]; then
    if command -v it2check >/dev/null 2>&1; then
      echo "Exporting iTerm2 preferences..."
      copy_with_manifest "${HOME}/Library/Preferences/com.googlecode.iterm2.plist" "config/com.googlecode.iterm2.plist" "OPTIONAL"
    else
      echo "Warning: USE_ITERM2 is enabled but iTerm2 is not installed (it2check not found)"
    fi
  fi

  echo "Scripts copied from local source directory"
else
  collect_error "No script source found. Please provide a local script source directory."
  exit 1
fi

# Copy Bash configuration
set_section "Copying Bash Configuration"

# Define source and destination paths for bash config
BASH_CONFIG_SOURCE="${HOME}/.config/bash"
BASH_CONFIG_DEST="${OUTPUT_PATH}/bash"

# Copy bash configuration directory with manifest tracking
copy_dir_with_manifest "${BASH_CONFIG_SOURCE}" "bash" "OPTIONAL" ".git|.claude|backups"

# Clean up development-specific files from bash config and manifest if they were copied
if [[ -d "${BASH_CONFIG_DEST}" ]]; then
  # Remove development-specific files that shouldn't be deployed
  for ITEM in .DS_Store .gitignore .shellcheckrc .yamllint secrets.sh "*.bak"; do
    rm -rf "${BASH_CONFIG_DEST:?}/${ITEM:?}" 2>/dev/null || true
    remove_from_manifest "bash/${ITEM}" "OPTIONAL"
  done

  # Set appropriate permissions
  chmod -R 644 "${BASH_CONFIG_DEST}/"*.sh 2>/dev/null || true
  chmod 644 "${BASH_CONFIG_DEST}/.bash_profile" 2>/dev/null || true
fi

# Copy README with variable substitution
if [[ -f "${SCRIPT_SOURCE_DIR}/docs/setup/firstboot-README.md" ]]; then
  echo "Processing README file..."
  sed "s/\${SERVER_NAME_LOWER}/${SERVER_NAME_LOWER}/g" \
    "${SCRIPT_SOURCE_DIR}/docs/setup/firstboot-README.md" >"${OUTPUT_PATH}/README.md"
  add_to_manifest "README.md" "REQUIRED"
  echo "✅ README creation"
else
  echo "⚠️ firstboot-README.md not found in source directory"
  add_to_manifest "README.md" "MISSING"
fi

echo "Setting file permissions..."
chmod 755 "${OUTPUT_PATH}/first-boot.sh" 2>/dev/null || true
chmod -R 755 "${OUTPUT_PATH}/scripts"
chmod -R 755 "${OUTPUT_PATH}/app-setup"
chmod 600 "${OUTPUT_PATH}/config/"* 2>/dev/null || true
chmod 600 "${OUTPUT_PATH}/app-setup/config/"* 2>/dev/null || true

# Ensure all shell scripts are executable
echo "Making all shell scripts executable..."
find "${OUTPUT_PATH}" -name '*.sh' -exec chmod -v a+rx {} \;

# Create Keychain manifest for server-side credential access
create_keychain_manifest

# Finalize external keychain and add to airdrop package
finalize_external_keychain

# Show collected errors and warnings
show_collected_issues

echo ""
echo "====== Setup Files Preparation Complete ======"
echo "The setup files at ${OUTPUT_PATH} are now ready for AirDrop."
echo "AirDrop this entire folder to your Mac Mini after completing the macOS setup wizard"
echo "and run ./first-boot.sh from the transferred directory root."

open "${OUTPUT_PATH}"

exit 0
